# Generated by Django 5.2.3 on 2025-06-24 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complexes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='رقم الوحدة')),
                ('floor', models.IntegerField(verbose_name='الطابق')),
                ('area', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='المساحة (م²)')),
                ('unit_type', models.CharField(choices=[('apartment', 'شقة'), ('villa', 'فيلا'), ('studio', 'استوديو')], max_length=20, verbose_name='نوع الوحدة')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='مشغولة؟')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='complexes.complex', verbose_name='المجمع')),
            ],
        ),
    ]
