# Generated by Django 5.2.3 on 2025-06-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='رقم الهوية')),
                ('phone', models.CharField(max_length=15, verbose_name='رقم الجوال')),
                ('contract_start', models.DateField(verbose_name='تاريخ بداية العقد')),
                ('contract_end', models.DateField(verbose_name='تاريخ نهاية العقد')),
            ],
        ),
    ]
