# Generated by Django 5.2.3 on 2025-06-24 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='units.unit', verbose_name='الوحدة'),
        ),
    ]
